name: CI Workflow

on:
  push:
    branches:
      
  pull_request:
    branches:
      

jobs:
  build:
    runs-on: ubuntu-latest  

     steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore dependencies for the Client project
      - name: Restore dependencies
        run: nuget restore Client/Client/Client/Client.csproj

      # Build the Client project
      - name: Build the Client project
        run: |
         "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" Client/Client/Client/Client.csproj /p:Configuration=Release

  arduino:
    runs-on: ubuntu-latest  # Використовуємо останню версію Ubuntu для CI

    steps:
      # Checkout the repository to get Arduino code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Arduino CLI for compiling Arduino code
      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: '0.19.2'  # Вказуємо версію Arduino CLI

      # Install the Arduino platform for AVR (e.g., Arduino Uno)
      - name: Install Arduino AVR platform
        run: arduino-cli core install arduino:avr  # Встановлюємо AVR core

      # Compile the Arduino project for Arduino Uno
      - name: Build Arduino Project
        run: |
          arduino-cli compile --fqbn arduino:avr:uno Server/Server/Server.ino  # Компілюємо для Arduino Uno
          
      # Upload the Arduino build result as an artifact
      - name: Upload Arduino Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: arduino-build  # Назва артефакту Arduino
          path: build/*  # Шлях до результатів компіляції Arduino